service: netflix-express-web-v2
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 30
  environment:
    MONGO_URI: "mongodb+srv://admin:10203040@bootcamp.7ra5k.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
    TOKEN_SECRET: "secret"
plugins:
  - serverless-plugin-typescript
  - serverless-offline
functions:
  app:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
